# This file defines the docker services
version: '3'
services:
    postgres:
        image: postgres
        env_file: database.env

    ancfinder:
            build: .
            env_file: app.env
            links:
                - postgres
            volumes:
                - static:/srv/app/static
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
            - ./uwsgi_params:/home/docker/code/uwsgi_params
            - /etc/letsencrypt:/etc/letsencrypt
            - /usr/share/nginx/html:/usr/share/nginx/html
            - static:/srv/app/static
        ports:
            - "80:80"
            - "443:443"
        links:
            - ancfinder
volumes:
    static: {}
